# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('top', models.FileField(upload_to='projects/top')),
                ('mdp', models.FileField(upload_to='projects/mdp')),
                ('gro', models.FileField(upload_to='projects/gro')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtc', models.FileField(upload_to='submissions')),
                ('edr', models.FileField(upload_to='submissions')),
                ('tpr', models.FileField(upload_to='submissions')),
                ('gro', models.FileField(upload_to='submissions')),
                ('log', models.FileField(upload_to='submissions')),
                ('cpt', models.FileField(upload_to='submissions')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(help_text='Name of the host that completed this WU', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tprs.Project')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
