# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tprs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtc', models.FileField(upload_to='alignments')),
                ('group', models.CharField(help_text='The gmx group used to assemble this alignment', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tprs.Submission')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
