# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprs', '0002_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='group_pdb',
            field=models.FileField(default='Prot-Masses', help_text='The pdb file representing the masses extracted during alignment.', upload_to='alignments'),
            preserve_default=False,
        ),
    ]
