# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprs', '0003_alignment_group_pdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='alignment',
            name='tpr_subset',
            field=models.CharField(default='Protein', help_text='Atom subset in the TPR extracted to match XTC atom counts.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alignment',
            name='group_pdb',
            field=models.FileField(help_text='The pdb file representing the masses extracted during alignment.', max_length=500, upload_to='alignments'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='xtc',
            field=models.FileField(max_length=500, upload_to='alignments'),
        ),
    ]
